### ISSUE TITLE
Close button

### ISSUE THREAD

**Issue by dbassendine** [iamphill/Bootstrap-Offcanvas#14]
Thanks for the awesome plugin!

I'd like to add a close button to provide a visual cue that allows for closing the sidebar.

I've looked at two approaches for this:

* add a second button to toggle the sidebar off, only visible when the sidebar is out
* change the text and icon of the existing button via JS, when the sidebar is out

Either way, although the classes imply the button is a "toggle" - I can click once on the button to open the sidebar, but when I click the button again, the sidebar does not close. The only UI way to close the sidebar appears to be clicking or tapping on some white space outside the sidebar.

It looks like I'll use the second approach above, and remove the "offcanvas-toggle" class when the sidebar is out, so when the user taps the button, it's the equivalent of tapping outside the sidebar.

How would you suggest implementing a close button using this plugin? Is there a way in the current version? Can we change the button into a true toggle in future versions, to make this easier?

Thanks! David

**Comment by quicoto** [comment]
Same here. Even in the example, the toggle button won't close the nav :(

**Comment by iamphill** [comment]
Hey guys! Sorry for the slow fix on this! But if you could try out the latest version, seems to of fixed it!

**Comment by kapilsipl** [comment]
Does anyone know how can I disable button (offcanvas-toggle) when menus open?
