### ISSUE TITLE
The example is broke again it looks like?

### ISSUE THREAD

**Issue by benzon** [iamphill/Bootstrap-Offcanvas#16]
When i visit the example or try to integrate this in to my site, there is huge issues, it will create a huge container, so the content is pushed further down the page, and the "gray" menu color dominates the page.

Besides that i would wish an inline example, where you just change the button in normal Navbar, to open the Offcanvas, so you can keep the bar in the top with your logo in it....

**Comment by keithmclaughlin** [comment]
When I try implementing this on my site I'm also seeing the huge container. It looks like the JavaScript is calculating the height of the viewport and adding that to the nav element even when the screen width is wider than 768px.

**Comment by iamphill** [comment]
The only way I can replicate this is by opening the menu and then resizing the browser to be desktop size again. Is this correct?

**Comment by sparkalow** [comment]
Just visiting the example on Chrome OSX does it for me.

I suspect `this.target.height($(window).outerHeight());` has something to do with it.

**Comment by iamphill** [comment]
Ok I can see what you mean now! I was just viewing it in mobile view instead of desktop size first. Will get a fix out now.
