### ISSUE TITLE
Keep bar with brand in canvas, move only navigation-DIV and search off-canvas

### ISSUE THREAD

**Issue by bmorejamie** [iamphill/Bootstrap-Offcanvas#19]
i'm reposting the issue that @cbieser raised, because i have the same issue.

you closed this issue, but it wasn't resolved... This would be great otherwise, but as is the logo (brand) gets stuck in the off-canvas sidebar and isn't visible when the navbar is hidden.

**Comment by iamphill** [comment]
I've just had a little look into it and understand the need for it now - there wasn't for a project this was made for. So going to look at this & probably bump the version to 2. Thanks!
