### ISSUE TITLE
The demo doesn't work in Android/Chrome browser

### ISSUE THREAD

**Issue by honucreative** [iamphill/Bootstrap-Offcanvas#2]
I have a Nexus 5, the demo page doesn't work, the menu button doesn't toggle the menu consistently, and when the menu finally reveals, any touch of the screen causes the menu to disappear.

**Comment by iamphill** [comment]
This could be because the CSS & JS on the demo page is very out of date. Will need to update.

**Comment by honucreative** [comment]
I had the same issue when I downloaded the project and tried it in a Bootstrap 3 project...

**Comment by iamphill** [comment]
@honucreative What version of android is it?

**Comment by ninetienne** [comment]
Hey Phill,

I'm experiencing the same problems. Android version is KitKat.

**Comment by iamphill** [comment]
@honucreative @ninetienne Ok, I'll try get hold of a kitkat device to test.

**Comment by iamphill** [comment]
Managed to replicate issue on android emulator. Will look for a fix.
