### ISSUE TITLE
window.on resize disables toggle button and scrolls to top on iOS devices 9.0.2 with Safari

### ISSUE THREAD

**Issue by Jungerislaender** [iamphill/Bootstrap-Offcanvas#22]
window.on resize disables toggle button and scrolls to top on iOS devices 9.0.2 with Safari.
Then when you reached top the toggle button works again.

Removing 
        $(window).on 'resize', ->
          $('body').css
            overflow: ''
            position: ''
          $('.navbar-offcanvas.in').each ->
            $(@).height('').removeClass 'in'
and replacing this with a enquire media query resolved this issue for me.

**Comment by iamphill** [comment]
@Jungerislaender Would you be able to test the branch https://github.com/iamphill/Bootstrap-Offcanvas/tree/v2 for me please?
