### ISSUE TITLE
Question: Version 2

### ISSUE THREAD

**Issue by kfirba** [iamphill/Bootstrap-Offcanvas#24]
Hey.

I'm glad I found this addon. Seems like it's gonna make my life easier :).

Is the v2 branch stable enough for usage? If not,  is there an estimation when it will be released? Also, will it present BC breaking changes?

**Comment by iamphill** [comment]
Hey! Version 2 should be pretty stable, I've not really changed much CSS but I have changed where the classes should be in the markup.

I'd pull down the branch and have a look at it :smile:

**Comment by kfirba** [comment]
@iamphill can this off canvas navigator work with vertical nav bar? Maybe with bootstrap group list? All I really want is to have another sidebar (besides a normal navigator) that will hide on xs and will be able to toggle open like this plugin presents. Is it possible?

**Comment by iamphill** [comment]
@kfirba I never built it with that in mind. I mainly built it to be for the main top horizontal navigation.

How about https://getbootstrap.com/examples/offcanvas/ ?

**Comment by kfirba** [comment]
@iamphil it doesn't feel good enough. I can still scroll the page content when the nav is open. There are no gestures as-well

Too bad I can't use your plugin :/
