### ISSUE TITLE
data toggle close function (x) does not work 

### ISSUE THREAD

**Issue by gward35** [iamphill/Bootstrap-Offcanvas#27]
When clicking the x on the menu it does not slide back? I have a mutli level menu in this drawer how can this issue be resolved? Currently the only way the user can close this menu is if they touch an area outside of the drawer. 

Here is a fiddle to illustrate http://jsfiddle.net/gward90/b25jgyox/2/

Your help is most appreciated.

**Comment by iamphill** [comment]
Hey @gward35 

So I've recently updated the plugin to v2 which improves a lot of stuff! Might be worth trying to upgrade to that? It will probably involve a slight re-work of your HTML so be sure to checkout the example https://github.com/iamphill/Bootstrap-Offcanvas/blob/master/example/index.html

**Comment by gward35** [comment]
Thanks @iamphill The menu now slides back when hitting the hamburger. Is there an easy way I can convert the hamburger icon to an x or something similar when the menu is open to signify "hit this to close" ?

Thank you again

**Comment by iamphill** [comment]
@gward35 Hmm... it should do that - it should animate the hamburger icon into a close icon. Do you have a hamburger icon or text?

If you have text - I'll probably have to make this an option (something I never thought about...)

**Comment by gward35** [comment]
@iamphill I am using BS hamburger icon I've updated my fiddle to illustrate

http://jsfiddle.net/gward90/b25jgyox/3/

**Comment by gward35** [comment]
@iamphill I'm sorry disregard I was missing the css part. This is wonderful thank you for your help.

**Comment by iamphill** [comment]
@gward35 glad to help :smile: glad we got it work :+1:
