### ISSUE TITLE
when click on search text box the menu is hidding auto

### ISSUE THREAD

**Issue by Arman143** [iamphill/Bootstrap-Offcanvas#28]
HI,
            i have add your code in my site but when i check this on mobile the canvas menu is auto hiding when click on search or  menu anywhere in canvas menu.. can you please help me with that .. i am not coder and i don't now jquery etc.
my website is: http://goo.gl/3bB8dA
check on mobile.. i have test it with android device mate 7

thanks

**Comment by Arman143** [comment]
i have record the mobile screen for easy understanding
video
http://tune.pk/video/6331849/mobizen-20151203-111353

**Comment by iamphill** [comment]
@Arman143 What version of the plugin are you using out of interest?

**Comment by gideonso** [comment]
@iamphill  Get the same problem. I use the latest mater download here.

Gideon

**Comment by andreuka** [comment]
getting the same in mobile chrome only!

**Comment by iamphill** [comment]
Can't reproduce. Can you try master?
