### ISSUE TITLE
Converting Offcanvas to Wordpress dynamic nav

### ISSUE THREAD

**Issue by responsivewebsg** [iamphill/Bootstrap-Offcanvas#29]
Hi, I am trying to convert my working index.html , bootstrap and offcanvas css and js. It is working fine on html but when I convert into the header.php on Wordpress using wp_bootstrap_navwalker.php. The offcanvas slides but does not show when collapes but does before collapsing though. I do not have a demo site at the moment but before are the files. Thanks in advance for the time:)

Below are the codes I've used. 

Index.html

<header>
    <nav class="navbar navbar-default" role="navigation">
        <div class="container no-top-padding">
            <div class="navbar-header">
                <a class="navbar-brand wow fadeInLeft" href="index.html"><img src="img/logo.png" width="294" height="124" class="img-responsive"></a>
                <button type="button" class="navbar-toggle offcanvas-toggle pull-right" data-toggle="offcanvas" data-target="#js-bootstrap-offcanvas">
                    <span class="sr-only">Toggle navigation</span>
                    <span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                    </span>
                </button>
            </div>
            <div class="navbar-offcanvas navbar-offcanvas-right" id="js-bootstrap-offcanvas">
                <div class="top-bar">
                    <ul class="top-bar-details">
                        <li><a href="#"><i class="fa fa-phone fa-lg"></i>   Call us now</a></li>
                        <li><a href="#"><i class="fa fa-calendar fa-lg"></i>    Book an appointment</a></li>
                        <li><a href="#"><i class="fa fa-users fa-lg"></i>   Careers</a>
                            <ul class="social-icons">                            
                                <li><a href="#"><i class="fa fa-facebook fa-lg"></i></a></li>
                                <li><a href="#"><i class="fa fa-google-plus fa-lg"></i></a></li>
                            </ul>
                        </li>                    
                    </ul>
                </div>
                <ul class="nav navbar-nav navbar-right">
                    <li class="active"><a href="index.html">Home</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">About <i class="fa fa-angle-down"></i></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Test</a></li>
                            <li><a href="#">Test</a></li>
                            <li><a href="#">Test</a></li>
                            <li><a href="#">Test</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Services <i class="fa fa-angle-down"></i></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Test</a></li>
                            <li><a href="#">Test</a></li>
                            <li><a href="#">Test</a></li>
                            <li><a href="#">Test</a></li>
                            <li><a href="#">Test</a></li>
                            <li><a href="bedbugs.html">Test</a></li>
                            <li><a href="#">Test</a></li>
                            <li><a href="#">Test</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Services <i class="fa fa-angle-down"></i></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Test</a></li>
                            <li><a href="#">Test</a></li>
                            <li><a href="#">Test</a></li>
                            <li><a href="#">Test</a></li>
                            <li><a href="#">Test</a></li>
                            <li><a href="#">Test</a></li>
                            <li><a href="#">Test</a></li>
                            <li><a href="#">Test</a></li>
                        </ul>
                    </li>
                    <li><a href="blog.html">Test</a></li>
                    <li><a href="index.html">Test</a></li>           
                </ul>
            </div>
        </div>
    </nav>
</header>

Header.php

		<header>				
			 <nav class="navbar navbar-default" role="navigation">
				<div class="container">          
					<div class="navbar-header">
						<a class="navbar-brand wow fadeInLeft" href="<?php echo home_url(); ?>">
							<img src="<?php bloginfo('stylesheet_directory'); ?>/img/logo.png" width="269" height="94" class="img-responsive">
						</a>
						 <button type="button" class="navbar-toggle offcanvas-toggle pull-right" data-toggle="offcanvas" data-target="#js-bootstrap-offcanvas">
		                    <span class="sr-only">Toggle navigation</span>
			                   	<span>
			                      <span class="icon-bar"></span>
			                      <span class="icon-bar"></span>
			                      <span class="icon-bar"></span>
                    			</span>
               			 </button>
              			 <a class="phone-no" href="#">6280 5666 (24/7)</a>
					</div>

					<div class="navbar-offcanvas navbar-offcanvas-right" id="js-bootstrap-offcanvas">
						<ul class="social-share">
		                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
		                    <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
		                    <li><a href="#" id="careers"><i>Careers</i></a></li>
		                    <a href="#" id="book">Book appt</a>
		                </ul>
		                <?php
				            wp_nav_menu( array(
				                'menu'              => 'primary',
				                'theme_location'    => 'primary',
				                'depth'             => 2,
				                'container'         => 'div',
                				'container_class'   => 'collapse navbar-collapse navbar-toggle offcanvas-toggle',
				        		'container_id'      => 'js-bootstrap-offcanvas',
				                'menu_class'        => 'nav navbar-nav navbar-right navbar-offcanvas navbar-offcanvas-right',
				                'fallback_cb'       => 'wp_bootstrap_navwalker::fallback',
				                'walker'            => new wp_bootstrap_navwalker())
				            );
				        ?>				        
					</div>
				</div> 
			</nav> 		
		</header> 

** After adding the menu dynamically in WP, it shows for desktop site.

**Comment by responsivewebsg** [comment]
Hi Phil,

Managed to correct the issue with the following code.

        		<?php
		            wp_nav_menu( array(
                        'menu'              => 'primary',
                        'theme_location'    => 'primary',
                        'depth'             => 2,
                        'container'         => 'js-bootstrap-offcanvas',
                        'container_class'   => 'collapse navbar-collapse navbar-toggle offcanvas-toggle js-bootstrap-offcanvas',
                        'container_id'      => 'js-bootstrap-offcanvas',
                        'menu_class'        => 'nav navbar-nav navbar-right',
                        'fallback_cb'       => 'wp_bootstrap_navwalker::fallback',
                        'walker'            => new wp_bootstrap_navwalker())
		            );
		        ?>

Thanks for the plugin anyways!

**Comment by iamphill** [comment]
@responsivewebsg Glad it is sorted! Sorry I didn't get round to looking into it!

**Comment by responsivewebsg** [comment]
Hi Phil,

 

No worries on that. 

 

Thank you.
