### ISSUE TITLE
Provided Examples Not Working

### ISSUE THREAD

**Issue by alenb** [iamphill/Bootstrap-Offcanvas#3]
Hi,

I downloaded the source files and ran the `example/index.html` locally and it did not load the menu at all when pressing the toggle button. Same thing happened when I tried the `test/index.html` example. The only example that actually works is the following hosted example: http://iamphill.github.io/Bootstrap-Offcanvas/example.html. Is there anything special happening with the hosted example?

Thank you very much for your help!

**Comment by iamphill** [comment]
@alenb are there are errors in the console?

**Comment by iamphill** [comment]
@alenb Did you also run `bower install` ?

**Comment by jlahijani** [comment]
I had this issue to.  It has to do with an incorrect path for loading jquery:
http://goo.gl/uAv0XQ

**Comment by iamphill** [comment]
In that case, to run the example, you'll need to run bower install
