### ISSUE TITLE
Offcanvas on iPad

### ISSUE THREAD

**Issue by kekkster** [iamphill/Bootstrap-Offcanvas#31]
Hi!
First of all, thanks for an amazing offcanvas menu. Works brilliantly!
So.. not an issue really. Rather a question.
I would like the offcanvas menu to work on an iPad/tablet. I tried to change the media query but didn´t get it to work. Is there anything else I can try?
Thanks in advance and once again, awesome work!

**Comment by EddyTheDove** [comment]
Hi,
Thanks for this awesome offcanvas nav. I have some issues on ipad. It doesn't work properly and cover the entire page. You can have a look on developer tool when you choose apple ipad as the device.
![screen shot 2016-01-09 at 3 23 34 am](https://cloud.githubusercontent.com/assets/8747601/12202954/968c979a-b680-11e5-865e-06fb028a54af.png)

**Comment by iamphill** [comment]
Hi @EddyTheDove, sorry for the slow reply! Just out of interest - what version are you running?

If you are using the sass version, it might just a case of changing the size in https://github.com/iamphill/Bootstrap-Offcanvas/blob/master/src/sass/_vars.scss#L14

**Comment by EddyTheDove** [comment]
Hi Phil and take you for your reply.
I am using the distribution version (css and js) from git.
If you download your repo and try it on the tablet, you will notice that bug. 
Could you please refer to my previous screenshot?

Cheers

**Comment by iamphill** [comment]
Sorry I see now. That is the default behaviour as it just goes off Bootstraps media queries to show this only on mobile.

If you want to have the offcanvas on tablet, i'd suggest using the sass version & change the variable values.

**Comment by EddyTheDove** [comment]
Thank you Phil. 
I will try some tweaks and let you know if I ever succeed

**Comment by kekkster** [comment]
Eddy hi-jacked my thread and I didn´t get an answer before it got closed. :)

Anywho... @iamphill, you mentioned sass. Isn´t there a way to do it with regular css?

**Comment by iamphill** [comment]
@kekkster yeah you can edit the CSS https://github.com/iamphill/Bootstrap-Offcanvas/blob/master/dist/css/bootstrap.offcanvas.css just changed the media query value. Let me know if you need some help! :+1:
