### ISSUE TITLE
Possible typos ?

### ISSUE THREAD

**Issue by MattMattV** [iamphill/Bootstrap-Offcanvas#33]
In the coffee script, there is 3 occurences of `offcavas` (lines 172 and 179)

Is that an error or is it normal ?

**Comment by iamphill** [comment]
@MattMattV is this an error you get when compiling?

**Comment by MattMattV** [comment]
No, I just saw them while reading your code

**Comment by iamphill** [comment]
Can't see where you are looking?

https://github.com/iamphill/Bootstrap-Offcanvas/blob/master/src/coffee/bootstrap.offcanvas.coffee#L172

https://github.com/iamphill/Bootstrap-Offcanvas/blob/master/src/coffee/bootstrap.offcanvas.coffee#L179

**Comment by MattMattV** [comment]
They are between quotes (: use the Ctrl+F to highlight them (offcanas)
