### ISSUE TITLE
Tap issue on larger touch screen devices when not in offcanvas mode

### ISSUE THREAD

**Issue by derickdsouza** [iamphill/Bootstrap-Offcanvas#35]
Hi, Thanks a bunch for this very useful script!

I have had the following issue:
When one taps on a page that is not in offcanvas mode, it resizes the navbar to height of the window.
This can be reproduced in the example page provided with Bootstrap-Offcanvas. I have tested it using Chrome DevTools' Device Mode (devices: Nexus 10 or Nexus 7 in landscape mode or any other larger device).  
I have added a check which seems to have fixed it:
```
OffcanvasTouch.prototype._touchStart = function(e) {
   this.startX = e.originalEvent.touches[0].pageX;
   if (this.element.is('.in')) {
          return this.element.height($(window).outerHeight());
   }
};
```
Not sure if this could have an impact on other functionality, will report it if I do come across any side effects.

**Comment by hongkongk** [comment]
thanks derickdsouza .

**Comment by papaiatis** [comment]
Thanks @derickdsouza  !
@iamphill Can you take a look on this as well? :wink:

**Comment by jhalvorson** [comment]
Thanks @derickdsouza, this fixed it for me too!
