### ISSUE TITLE
The offcanvas navbar is not working if the navbar definition is loaded by ajax

### ISSUE THREAD

**Issue by papaiatis** [iamphill/Bootstrap-Offcanvas#36]
I have an AngularJs application in which the header part is defined in a separate file thus it is loaded into the HTML by an AJAX call. This case the navbar toggle button does not work. It won't open the offcanvas menu. 
However if I re-run the entire bootstrap-offcanvas javascript code in F12 console the navbar toggle works. 
So this means this component does not support navbar-s that are loaded by AJAX.
Please add support for it!

**Comment by iamphill** [comment]
Do you have a demo app that you could share?

**Comment by papaiatis** [comment]
I've made you one: http://plnkr.co/edit/ZmUVTgp6xJctlZ0Xk14R?p=preview
The trick is `ng-include` which loads the specified html file into that exact spot.

**Comment by iamphill** [comment]
Thanks! I'll look into getting a fix for this :smile:

**Comment by papaiatis** [comment]
Thanks! It would be awesome if you could fix it soon :wink:

**Comment by papaiatis** [comment]
Any update on this? I'm eager to intergrate it into my website!

**Comment by iamphill** [comment]
Unfortunately it's s bit harder than I originally though. I think I need to do a bit of a refactor of how it works, which is something I want to do anyway. However I don't have the time to do this at the moment. 

Is there anyway you can use the class I've created? It should be a global object that you should be able to init from in angular.

**Comment by papaiatis** [comment]
That could work. How can I initialize your class?

**Comment by iamphill** [comment]
You should be able to use new Offcanvas(TOGGLE ELEMENT)

**Comment by papaiatis** [comment]
Sorry, but I'm not sure what to write into TOGGLE ELEMENT.
I have this as a toggle button:

```
<button type="button" class="navbar-toggle offcanvas-toggle ng-scope" data-toggle="offcanvas" data-target="#js-bootstrap-offcanvas">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
</button>
```

I copied it from your example: http://iamphill.github.io/Bootstrap-Offcanvas/example.html

**Comment by papaiatis** [comment]
In the meanwhile I've updated the Plunkr code. Look for the "init Offcanvas here" line. That should be the place to put your Offcanvas init logic.

http://plnkr.co/edit/ZmUVTgp6xJctlZ0Xk14R?p=preview

**Comment by iamphill** [comment]
I'll fork the plunkr & get it working :smile:

**Comment by papaiatis** [comment]
Got it! `new Offcanvas($('[data-toggle="offcanvas"]'));`

**Comment by iamphill** [comment]
Nice one! I was just about to send it back with that!

Happy to close?

**Comment by papaiatis** [comment]
Sure I am! Thanks a lot :-) Amazing support!

**Comment by iamphill** [comment]
You're welcome! :+1:

**Comment by kingkero** [comment]
This should be way more prominent! Have been trying make this plugin work with require.js for a couple of hours.
```
require([
  'backbone',
  'jquery',
  'bootstrapOffcanvas'
], function (Backbone, $, Offcanvas) {
  new Offcanvas($('[data-toggle="offcanvas"]'));
  //...
});
```
Just started using require.js and Backbone, so not sure if this is best practice - but it works!
