### ISSUE TITLE
Please add support for manually close the navbar using trigger

### ISSUE THREAD

**Issue by papaiatis** [iamphill/Bootstrap-Offcanvas#37]
As per in the manual there is a `offcanvas.toggle` trigger I can fire which opens/closes the navbar, eg.:

    $("#js-bootstrap-offcanvas").trigger("offcanvas.toggle");

I'd like to have a similar trigger which not triggers but closes the navbar if it was open, something like:

    $("#js-bootstrap-offcanvas").trigger("offcanvas.close");

This is also required for my Angular (ajax) application which uses HTML5 Push States to navigate between different pages. When a new state (or page) is loaded the opened offcanvas navbar remains opened. I need it to be closed this case.

**Comment by iamphill** [comment]
New version with this https://github.com/iamphill/Bootstrap-Offcanvas/releases/tag/2.2.0

**Comment by papaiatis** [comment]
Thanks, it works! Consider updating your Readme.md as well :wink:

**Comment by iamphill** [comment]
Good spot! Updated :+1:
