### ISSUE TITLE
v2.1.1: index.html in the example folder doesn't seem to work.

### ISSUE THREAD

**Issue by potentstudios** [iamphill/Bootstrap-Offcanvas#38]
Not sure If I'm missing something but the index.html file in the example folder of the .zip doesn't work in v2.1.1. The menu icon doesn't trigger the off canvas menu. Is anyone else having this issue?

**Comment by iamphill** [comment]
have you done both `npm install` & `bower install` to get deps?

**Comment by rmstinson** [comment]
Hi everyone. I'm also having the same issue as @potentstudios in which the example index.html file doesn't work. @iamphill I tried to install both npm install and bower install and received the errors: 

```
$ bower install
bower jquery#~2.1.1         not-cached git://github.com/jquery/jquery-dist.git#~2.1.1
bower jquery#~2.1.1            resolve git://github.com/jquery/jquery-dist.git#~2.1.1
bower jquery#~2.1.1            ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/jquery/jquery-dist.git", exit code of #128 fatal: Could not read from remote repository.  Please make sure you have the correct access rights and the repository exists.

Additional error details:
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by PascaleBeier** [comment]
This issue can be resolved by instructing git to use https instead of ssh: 

`git config --global url."https://".insteadOf git://
`
