### ISSUE TITLE
Only allowing one opened (sub)menu

### ISSUE THREAD

**Issue by PascaleBeier** [iamphill/Bootstrap-Offcanvas#43]
ping @iamphill 

What is the best approach to only allow one menu to be opened, e.g. showing its children?

For instance:

Assuming my page tree looked like this:

```
Page A
|_ Child
|_ Child
Page B
|_ Child
|_ Child
```

When the user visits my site on a mobile device:

```
Page A
Page B
```

When the user opens Page A

```
Page A
|_ Child
|_ Child
Page B
```

Now I want the following behaviour **when the user opens Page B while Page A is showing its children:**

```
Page A
Page B
|_ Child
|_ Child
```

Any hints? :) Thanks!

**Comment by iamphill** [comment]
Do you mean in the dropdown you want a list of collapsible links?

**Comment by PascaleBeier** [comment]
Not at all! Poor wording from my side.

I want only one menu to be expanded - So when a user expands a menu and tries expanding another - the previous expanded menu is collapsed. 

Default behaviour is that all menus can be expanded, but I certainly want to change this to the just described.
