### ISSUE TITLE
Menu behavior on iPhone and iPad

### ISSUE THREAD

**Issue by pieterss** [iamphill/Bootstrap-Offcanvas#45]
I implemented your plugin on two sites and noticed that on iPhone / iPad only the menu opens from left top to right bottom on toggle in stead of from left to right.

**Comment by iamphill** [comment]
What ios version?

**Comment by pieterss** [comment]
9.3.4 (and before). The same behavior occurs on your demo page http://iamphill.github.io/Bootstrap-Offcanvas/example.html, but is less manifest because the menu is light-colored on a white body background. Try making it black :)

**Comment by thomasgallagher** [comment]
I'm seeing this too - anything I can do to help?

**Comment by thomasgallagher** [comment]
This fixed it for me:

```
.navbar-offcanvas {
    height: 100%;
}
```
