### ISSUE TITLE
Dropdown doesn´t work correctly

### ISSUE THREAD

**Issue by DonTermi** [iamphill/Bootstrap-Offcanvas#46]
Hi,

I have Bootstrap 3.3.6 with bootstrap css + js loaded. After this  your offcanvas js is loaded. But when I open at offcanvas the submenu and I click into empty space on offcanvas, the submenu is not closed and there are some other style problems.

Can you fix this that your offcanvas version work with submenus?

**Comment by iamphill** [comment]
So you want an empty space tap to hide opened submenus?

**Comment by PascaleBeier** [comment]
This is not the default behaviour of bootstrap's dropdowns though.
