### ISSUE TITLE
Offcanvas menu automatically closes when input is clicked

### ISSUE THREAD

**Issue by AaronKazah** [iamphill/Bootstrap-Offcanvas#47]
The offcanvas menu automatically closes when the input is clicked. I tried debugging it however I couldn't understand your js, no comments anywhere.

**Comment by iamphill** [comment]
What browser is this on?

**Comment by AaronKazah** [comment]
That was a quick reply, and it's present in the chrome browser, I ended up redesigning the search bar and moved it out of the off canvas menu.

**Comment by iamphill** [comment]
@AaronKazah Just tried on Chrome & I can't see the issue.
