### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by viosys** [iamphill/Bootstrap-Offcanvas#64]
Hi,
could you make this repository usable by Composer / Packagist.
See: [http://blog.jgrossi.com/2013/creating-your-first-composer-packagist-package/](http://blog.jgrossi.com/2013/creating-your-first-composer-packagist-package/)
Thanks in advance
Falko

**Comment by iamphill** [comment]
I dont think I am going to do this. Feel free to create your own package though & I can link in the README
