### ISSUE TITLE
Incompatible with Turbolinks

### ISSUE THREAD

**Issue by matthewscalf** [iamphill/Bootstrap-Offcanvas#73]
How can re-instantiate the off canvas menu with a turbo link load? Basically the body is replaced with ajax content, so the scripts are not called again, but I can fire a function on turbo link load, so I could re-setup the object but I cannot see how.

**Comment by matthewscalf** [comment]
I figured out a workaround, but feels kind of hacky. Let me know if there is a better way.

**Comment by iamphill** [comment]
@matthewscalf hey! Sorry the slow reply to this. You could just init the offcanvas script in the Turbolinks ready event.

**Comment by iamphill** [comment]
Ah to do that we probably need #66 😞
