### ISSUE TITLE
Manually open menu when click on button not in menu

### ISSUE THREAD

**Issue by lonerunner** [iamphill/Bootstrap-Offcanvas#79]
The documentation suggests to use 

$("#js-cart-offcanvas").trigger("offcanvas.open");

if we want to manually trigger to open menu but this does not work when i click. I don't see animation and any class elements changes in debug console in chrome.

I have product list and when i click on product i want to add product details to menu and open menu

```
jQuery(document).ready(function($) {


	order = function(elem) {
		$("#js-cart-offcanvas").trigger("offcanvas.open");
		$(".cart-offcanvas").append(
			'<div class="itemdetails">' +
			'</div>'
		);

```

But it seems it doesn't work.

**Comment by anephew** [comment]
Same here. Not work
