### ISSUE TITLE
css lost on resizing

### ISSUE THREAD

**Issue by sajjadmubashar** [iamphill/Bootstrap-Offcanvas#8]
I have implemented the provided menu but without bower simply copied css and js files and it worked wonderfully but the only issue i have faced using chrome if i open up menu by toggle button after minimizing browser window it works and if i click any where out side and maximize the browser it goes well but,,,,if i open up menu after minimizing chrome browser and click on maximize button without clicking any where on the page my whole page looses its css. Please help.

**Comment by iamphill** [comment]
@sajjadmubashar Does this happen on http://iamphill.github.io/Bootstrap-Offcanvas/example.html as well? Is this windows or mac chrome?

**Comment by sajjadmubashar** [comment]
@iamphill I am extremely sorry i stated little early,,,in fact it was perfectly working i was not implementing body tag properly as per example. Now its perfectly supporting me :+1:
