### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by DaveLindberg** [iamphill/Bootstrap-Offcanvas#9]
I'm getting the following error when loading my page with ````bootstrap.offcanvas.js```` installed: 

````Uncaught TypeError: undefined is not a functionbootstrap.offcanvas.js?ver=4.0:229 (anonymous function)bootstrap.offcanvas.js?ver=4.0:253 (anonymous function)````

Loading ````bootstrap.offcanvas.min.js```` produces the same result.

**Comment by iamphill** [comment]
@DaveLindberg What line is the error on? Do you get the error on http://iamphill.github.io/Bootstrap-Offcanvas/example.html?

**Comment by DaveLindberg** [comment]
looks like the error is on line 229. JSHint throws warnings on:
**line 233** 
````return oc =```` "Did you mean to return a conditional instead of an assignment? — column 18"
**line 237** 
````return $(this).on('click', function(e) {```` "'e' is defined but never used. — column 43"
I installed the components using bower.

**Comment by iamphill** [comment]
@DaveLindberg Hmm.. 229 would be https://github.com/iamphill/Bootstrap-Offcanvas/blob/master/dist/js/bootstrap.offcanvas.js#L229 which would surely mean that `$` isn't available. jQuery is available right?

**Comment by DaveLindberg** [comment]
Confirmed, jQuery is loading properly — before the bootstrap.offcanvas.js

**Comment by iamphill** [comment]
@DaveLindberg Could you upload a demo somewhere where it isn't working?

**Comment by DaveLindberg** [comment]
See http://webdev.davelindberg.com/

**Comment by iamphill** [comment]
@DaveLindberg Ah I see the issue, angularJS redefines the `$`. Will get a fix out ASAP.

**Comment by DaveLindberg** [comment]
Fantastic, thanks!

**Comment by iamphill** [comment]
@DaveLindberg Just released 1.3.5 if you could try that.

**Comment by DaveLindberg** [comment]
I've posted the v1.3.5 version to http://webdev.davelindberg.com/
Still getting an error. Line 149?

**Comment by iamphill** [comment]
@DaveLindberg Just checked your demo, and it is still showing the older version?

Just created a PR anyway with a test. Could you try using #10 ?

**Comment by DaveLindberg** [comment]
#10 is working fine on my local install. Oddly, it still throws an error on webdev. I've check the two files and found no diff, not sure what's happening here?

**Comment by iamphill** [comment]
@DaveLindberg Your one http://webdev.davelindberg.com/wp-content/themes/angwobo/bower_components/bootstrap-offcanvas/dist/js/bootstrap.offcanvas.js?ver=4.1.1 looks different to https://raw.githubusercontent.com/iamphill/Bootstrap-Offcanvas/dollar-fix/dist/js/bootstrap.offcanvas.js

**Comment by DaveLindberg** [comment]
Thx. Not sure why, but there's a trailing newline on the webdev version that I can't get rid of. Other than that, the latest version should be in place.

**Comment by iamphill** [comment]
@DaveLindberg Cool, will get it merged in.

Styling on your version is off. Looks like you haven't included Bootstrap.
